name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: Install MinGW
  # You may pin to the exact commit or the version.
  # uses: egor-tensin/setup-mingw@f3c5d799aadf8fa230ac67a422b01dd085bbc96b
        uses: egor-tensin/setup-mingw@v2
        with:
          # Target platform
          platform: x64 # optional, default is x64
          # Install Cygwin packages
          cygwin: 0 # optional, default is 0
          # Enable static linking workaround
          static: 1 # optional, default is 1
          # Set up cc/c++ executables
          cc: 1 # optional, default is 1
          # On Cygwin, replace executable symlinks with hardlinks
          hardlinks: 0# optional, default is 0
      - uses: actions/checkout@v3
      - run: dir
      - run: setup-mingw64.ps1
